---
- name: Configure Domain Controller
  hosts: domain_controllers
  gather_facts: yes
  vars:
    ad_domain: 'adlab.local'
    admin_password: 'LabPass1'
    domain_ip: '192.168.10.100'
  tasks:
  
#### Workaround to allow unpublished remoteapps working
    - name: Allow unlisted RemoteApps and restart RDP service
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
        name: fAllowUnlistedRemotePrograms
        data: 1
        type: dword
        state: present

    - name: Restart Remote Desktop Services (TermService)
      ansible.windows.win_service:
        name: TermService
        state: restarted
        force_dependent_services: yes
        
        ### Added to disable NLA and fix auth issue.        
    - name: Disable NLA for RDP
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
        name: UserAuthentication
        data: 0
        type: dword

    - name: Restart RD
      win_service:
        name: TermService
        state: restarted
        force_dependent_services: yes
        
    - name: Reboot again
      ansible.windows.win_reboot:
        msg: 'Rebooting after AD forest installation.'
        pre_reboot_delay: 10
        post_reboot_delay: 20
        reboot_timeout: 300
