# atomic_tests.yml
# Ansible Playbook to run high-value Atomic Red Team tests on lab endpoints
- name: Run Atomic Red Team tests on the workstation.
  hosts: workstations
  gather_facts: no
  vars:
    techniques:
      - T1059  # Command and Scripting Interpreter
      - T1027  # Obfuscated Files or Information
      - T1112  # Modify Registry
      - T1003  # Credential Dumping
  tasks:
    - name: Import ART module and run tests
      win_shell: |
        Install-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
    - name: Import ART module and run tests
      win_shell: |
        Invoke-AtomicTest {{ item }}-GetPreqs -TestNumbers 1 -CheckPrereqs
      args:
        executable: powershell.exe
      loop: "{{ techniques }}"
      register: atomic_output

    - name: Display output
      debug:
        var: atomic_output.results

    - name: Reminder to analyze logs in HELK
      debug:
        msg: "Check Kibana for logs from Sysmon and Winlogbeat related to the executed techniques."
